<?php
    $lang['number']   = 'No. Referensi';
    $lang['date']     = 'Tanggal';
    $lang['time']     = 'Waktu';
    $lang['due']      = 'Jatuh Tempo';
    $lang['to']       = 'Untuk';
    $lang['from']     = 'Dari';
    $lang['product']  = 'Produk';
    $lang['qty']      = 'Qty';
    $lang['price']    = 'Harga';
    $lang['discount'] = 'Diskon';
    $lang['vat']      = 'Pajak';
    $lang['total']    = 'Total';
    $lang['page']     = 'Halaman';
    $lang['page_of']  = 'dari';
